version: '3.1'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sanjaylakum352